name: unit-tests
run-name: Unit Test Action
on: [push]
jobs:
  run-unit-test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: autoconf
        run: autoconf -vfi
      - name: configure
        run: ./configure
      - name: build
        run: make
      - name: test
        run: src/test