name: unit-tests
run-name: Unit Test Action
on: 
  push
    branches:
      - master
      - dev
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: udpate packages
        run: sudo apt-get update -y
      - name: install libbenchmark-dev 
        run: sudo apt-get install libbenchmark-dev
      - name: checkout module
        run: git submodule update --init --recursive
      - name: autoreconf
        run: autoreconf -vfi
      - name: configure
        run: ./configure
      - name: build
        run: make
      - name: test
        run: src/test

  
